version: '2'
services:
    server:
      container_name: discord_music_server
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 8060:8080
      restart: always
      links:
        - discord_database:database
    database:
      container_name: discord_database
      image: mongo:3.4.2
      restart: always
      volumes:
        - ../opt/mongodb:/data/db
      ports:
        - 27044:27017
      command: mongod --auth