version: '2'
services:
    server:
      container_name: discord_music_server
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 8060:8080
      restart: always
      links:
        - database:database
    database:
      container_name: discord_database
      image: mongo:3.4.2
      restart: always
      volumes:
        - ../opt/mongodb:/data/db
      ports:
        - 27044:27017
        # Note: By default mongodb has no admin / root user defined
        # for this reason you will have to enter mongodb (remove --auth flag to enter without auth first) instance within container docker exec -it discord_database /bin/bash
        # and create admin user manually db.createUser
        # since containers restart automatically, after successful root user creation the container should log in without any problems
      command: mongod --auth